### ISSUE TITLE
hello_http_2: {"error":"transport is closing","code":14}

### ISSUE THREAD

**Issue by JesseYan** [jergoo/go-grpc-example#10]
**1. hello_http_2:  I use http instead of https ,
codes are like this, and in shell:**

> curl -X POST -k http://127.0.0.1:50051/example/echo -d '{"name": "Jesse Yan"}' 

**but have problems :** 

> {"error":"transport is closing","code":14}

```go
// httpdemo/server/main.go
package main

import (
	"crypto/tls"
	"io/ioutil"
	"net"
	"net/http"
	"strings"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	pb "proto/bi/service/httpsdemo"
	"golang.org/x/net/context"
	"golang.org/x/net/http2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/grpclog"
)

// 定义helloHTTPService并实现约定的接口
type helloHTTPService struct{}

// HelloHTTPService Hello HTTP服务
var HelloHTTPService = helloHTTPService{}

// SayHello 实现Hello服务接口
func (h helloHTTPService) SayHello(ctx context.Context, in *pb.HelloHTTPRequest) (*pb.HelloHTTPResponse, error) {
	resp := new(pb.HelloHTTPResponse)
	resp.Message = "Hello " + in.Name + "."

	return resp, nil
}

func main() {
	endpoint := "127.0.0.1:50051"
	conn, err := net.Listen("tcp", endpoint)
	if err != nil {
		grpclog.Fatalf("TCP Listen err:%v\n", err)
	}

	// grpc server
	grpcServer := grpc.NewServer()
	pb.RegisterHelloHTTPServer(grpcServer, HelloHTTPService)

	// gw server
	ctx := context.Background()
	dopts := []grpc.DialOption{grpc.WithInsecure()}
	gwmux := runtime.NewServeMux()
	if err = pb.RegisterHelloHTTPHandlerFromEndpoint(ctx, gwmux, endpoint, dopts); err != nil {
		grpclog.Fatalf("Failed to register gw server: %v\n", err)
	}

	// http服务
	mux := http.NewServeMux()
	mux.Handle("/", gwmux)

	httpServer := &http.Server{
		Addr:      endpoint,
		Handler:   grpcHandlerFunc(grpcServer, mux),
		//TLSConfig: getTLSConfig(),
	}

	grpclog.Infof("gRPC and https listen on: %s\n", endpoint)

	//if err = srv.Serve(tls.NewListener(conn, srv.TLSConfig)); err != nil {
	if err = httpServer.Serve(conn); err != nil {
		grpclog.Fatal("ListenAndServe: ", err)
	}

	return
}

// grpcHandlerFunc returns an http.Handler that delegates to grpcServer on incoming gRPC
// connections or otherHandler otherwise. Copied from cockroachdb.
func grpcHandlerFunc(grpcServer *grpc.Server, otherHandler http.Handler) http.Handler {
	if otherHandler == nil {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			grpcServer.ServeHTTP(w, r)
		})
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.ProtoMajor == 2 && strings.Contains(r.Header.Get("Content-Type"), "application/grpc") {
			grpcServer.ServeHTTP(w, r)
		} else {
			otherHandler.ServeHTTP(w, r)
		}
	})
}
```

2. **I also got problems:**

> go run main.go
FATAL: 2018/03/20 16:26:09 rpc error: code = Unavailable desc = transport is closing

**when I request RPC in rpc_client like this：**
```go
// httpdemo/client/main.go
package main

import (
	pb "github.com/jergoo/go-grpc-example/proto/hello_http" // 引入proto包

	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/grpclog"
)

const (
	// Address gRPC服务地址
	Address = "127.0.0.1:50052"
)

func main() {
	// TLS连接
	//creds, err := credentials.NewClientTLSFromFile("../keys/server.pem", "server name")
	//if err != nil {
	//	grpclog.Fatalf("Failed to create TLS credentials %v", err)
	//}
	//conn, err := grpc.Dial(Address, grpc.WithTransportCredentials(creds))
	conn, err := grpc.Dial(Address, grpc.WithInsecure())

	if err != nil {
		grpclog.Fatalln(err)
	}

	defer conn.Close()

	// 初始化客户端
	c := pb.NewHelloHTTPClient(conn)

	// 调用方法
	reqBody := new(pb.HelloHTTPRequest)
	reqBody.Name = "Jesse Yan"
	r, err := c.SayHello(context.Background(), reqBody)

	if err != nil {
		grpclog.Fatalln(err)
	}

	grpclog.Println(r.Message)
}

// OR: curl -X POST -k https://localhost:50052/example/echo -d '{"name": "gRPC-HTTP is working!"}'

```

**Comment by JesseYan** [comment]
set **export GODEBUG=http2debug=2** in shell, and got this in rpc_server main.go:
```shell
....
2018/03/20 16:26:21 http2: Framer 0xc420c8c000: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc420ec8000: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc420ec82a0: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc420c8c460: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc420ec8620: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc420c8c000: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc420ec80e0: wrote SETTINGS len=0
2018/03/20 16:26:21 http2: Framer 0xc422758000: wrote SETTINGS len=0
...
```

**Comment by jergoo** [comment]
@JesseYan It's normal when you use http

**Comment by jergoo** [comment]
@JesseYan 
It's normal when use http, I got this error too.
You can read my [documentation](https://jergoo.gitbooks.io/go-grpc-practice-guide/content/chapter3/gateway.html) about this project, I think this is because http2 requires https.

**Comment by JesseYan** [comment]
@jergoo 我想应该不是http2的问题，我换了一种方式，同样用http，我用两个端口，分别分开用在server和gateway上，可以正常运行。server.go, gateway.go分别见如下：
```go
//server/main.go
package main

import (
	"net"
	pb "proto/bi/service/httpsdemo"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"
	"log"
)

// 定义helloHTTPService并实现约定的接口
type helloHTTPService struct{}

// HelloHTTPService Hello HTTP服务
var HelloHTTPService = helloHTTPService{}

// SayHello 实现Hello服务接口
func (h helloHTTPService) SayHello(ctx context.Context, in *pb.HelloHTTPRequest) (*pb.HelloHTTPResponse, error) {
	resp := new(pb.HelloHTTPResponse)
	resp.Message = "Hello " + in.Name + "."

	return resp, nil
}

func main() {
	endpoint := "127.0.0.1:50051"
	lis, err := net.Listen("tcp", endpoint)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterHelloHTTPServer(s, &HelloHTTPService)
	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
```


```go
//gateway/main.go
package main

import (
	"flag"
	"net/http"

	"github.com/golang/glog"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"golang.org/x/net/context"
	"google.golang.org/grpc"

	gw "proto/bi/service/httpsdemo"
)

var (
	echoEndpoint = flag.String("echo_endpoint", "127.0.0.1:50051", "endpoint of YourService")
)

func run() error {
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	mux := runtime.NewServeMux()
	opts := []grpc.DialOption{grpc.WithInsecure()}
	err := gw.RegisterHelloHTTPHandlerFromEndpoint(ctx, mux, *echoEndpoint, opts)
	if err != nil {
		return err
	}

	return http.ListenAndServe(":8888", mux)
}

func main() {
	flag.Parse()
	defer glog.Flush()

	if err := run(); err != nil {
		glog.Fatal(err)
	}
}
```

```shell
curl -X POST -k http://127.0.0.1:8888/example/echo -d '{"name": "Jesse Yan"}'
```

**Comment by jergoo** [comment]
@JesseYan hello_http里面的示例就是分开做的，但是你注意下分开后的server.go，是不能直接用http请求的

**Comment by fengweiqiang** [comment]
使用protoc  生成的没有SayHello

- `// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	HelloRequest
	HelloReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// HelloRequest 请求结构
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto1.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// HelloReply 响应结构
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto1.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto1.RegisterType((*HelloReply)(nil), "proto.HelloReply")
}

func init() { proto1.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4a, 0x5c, 0x3c, 0x1e,
	0x20, 0xd1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc,
	0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x8d, 0x8b, 0x0b, 0xaa, 0xa6,
	0x20, 0xa7, 0x52, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x1d, 0xa6, 0x08, 0xc6,
	0x35, 0xb2, 0xe5, 0x62, 0x05, 0xab, 0x13, 0x32, 0xe1, 0xe2, 0x08, 0x4e, 0xac, 0x84, 0xb0, 0x85,
	0x21, 0xf6, 0xe9, 0x21, 0xdb, 0x22, 0x25, 0x88, 0x2a, 0x58, 0x90, 0x53, 0xa9, 0xc4, 0x90, 0xc4,
	0x06, 0x16, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x9d, 0x53, 0x77, 0xa7, 0x00, 0x00,
	0x00,
}
`
