### ISSUE TITLE
hello 范例中俩个问题

### ISSUE THREAD

**Issue by niaiwomattt** [jergoo/go-grpc-example#11]
1.server 中 SayHello 绑定的struct 为啥是 T，而不是 *T ？
2.grpclog.Pringln() 不会在控制台输出内容，你的怎么输出的 ？我是自己加了fmt 的方法才打了出来，我以为是我自己哪儿复制错了呢。

**Comment by jergoo** [comment]
@niaiwomattt 
1. 这里没有为啥，用*T也一样，只要RegisterServier那里传进去的参数实现了我们生成的server interface：https://github.com/jergoo/go-grpc-example/blob/92f5cabb7d8b1197106f3ec2ad31e5eed0ed6072/proto/hello/hello.pb.go#L109

2. 这个你不用纠结，一个日志库而已，我们用的版本也不一定一样
