### ISSUE TITLE
hello_http_2不成功

### ISSUE THREAD

**Issue by waytai** [jergoo/go-grpc-example#2]
运行hello_http_2不成功，另外hello_http怎么用？
一直报错
2017/08/09 14:27:13 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:13 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:13 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2017/08/09 14:27:14 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.

**Comment by jergoo** [comment]
@waytai 这个问题修复了，开启http服务时增加了http2 TLS参数，具体看[commit：修复hello_http_2](https://github.com/jergoo/go-grpc-example/commit/d96e6e676dae9783d4207f8cb39c61cfc8ac06eb)，注意90行。

另外，你之前提出改用`srv.ListenAndServeTLS`方法，我测试了也可以使用，只是在初始化srv时会尝试一次连接并且会失败，启动时会有一次连接失败的log，暂时没找到这个操作是在哪里发起的。
