### ISSUE TITLE
hello_trace项目，物理机如何访问虚拟机debug页面？

### ISSUE THREAD

**Issue by EDDYCJY** [jergoo/go-grpc-example#7]
您好，

我在SF上按照 https://segmentfault.com/a/1190000008087436 做或使用 hello_trace 中的代码，

虽然 server、client都能够运行，但只能通过虚拟机本地curl访问`127.0.0.1:50051/debug/events`，

目前我是物理机是windows，虚拟是linux的方式，想要通过物理机访问`x.x.x.x:50051/debug/events`，

并且也修改了`http.ListenAndServe`为`go http.ListenAndServe("0.0.0.0:50051", nil)`。

但是依旧无法访问，
请问应该如何编写或修改什么配置，才能达到物理机能访问看到虚拟机的debug页面呢？

谢谢。

**Comment by jergoo** [comment]
这是你虚拟机的问题，程序你改成 0.0.0.0 没有问题，如果是用 virtual Box / VMware 装的虚拟机，每个机器都有它自己的IP，和你的本地主机是在一个局域网的，可以直接访问，比如：虚拟机IP是 192.168.2.100， 那在你本地主机可以直接访问 192.168.2.100:50051/debug/events

**Comment by EDDYCJY** [comment]
好的 我以为是Grpc的trace有针对外网访问的内部配置，
我再另外排查下具体原因。

感谢。
