### ISSUE TITLE
hello_trace项目，页面仅显示了h1标题，table标签为空白

### ISSUE THREAD

**Issue by EDDYCJY** [jergoo/go-grpc-example#8]
jergoo你好，上次的外网访问问题我已经解决。

但是，有新的问题 :(

目前我使用**仓库里的hello_trace项目**代码运行，能够访问到页面，
但是仅显示了h1标题（/debug/events、/debug/requests），具体的trace内容都不显示，直接空白的table标签。

请问是什么原因呢，谢谢！

---

网页样子如下（就是标题以下都是空白）：
<h1>/debug/requests</h1> 
 
  
  <table id="tr-status"> 
   </table>

**Comment by jergoo** [comment]
@EDDYCJY 只运行服务端时访问是这样的，因为还没有任何请求记录，你开启server后，再运行一次client，刷新页面看一下

**Comment by EDDYCJY** [comment]
我的确有去请求，我是运行了服务端后，再运行客户端，然后刷新`trace`的2个页面。
依旧空白，您那边没有这问题吗？

谢谢。

**Comment by jergoo** [comment]
@EDDYCJY 我本地直接运行的示例代码，页面显示正常。

**Comment by hy93** [comment]
我也遇到了楼主一样的问题，jergoo看到我
