### ISSUE TITLE
hello_http_2/server/main.go运行报错

### ISSUE THREAD

**Issue by hy93** [jergoo/go-grpc-example#9]
`FATAL: 2018/02/28 10:06:14 Failed to create server TLS credentials open ../../keys/server.pem: no such file or directory
`
请教，那个文件明明在的，运行就是找不到，是为啥??感谢

**Comment by hy93** [comment]
试了一下使用绝对地址是可以的，相对地址不行，是为啥呢？

**Comment by jergoo** [comment]
@hy93 你应该是在外层目录执行的`go run`命令，这样使用相对路径确实会有问题，你可以进入server目录执行

**Comment by hy93** [comment]
的确是这样，谢谢

**Comment by EDDYCJY** [comment]
其实我想请问下@jergoo 有没有办法兼容这2种命令执行方式
毕竟在我们实际应用中有许多配置文件也是走的相对路径，但是一旦执行命令所在的目录不同，就会导致路径出错了

**Comment by hy93** [comment]
那感觉好像只有用绝对路径了

**Comment by EDDYCJY** [comment]
@hy93 绝对路径更加不现实了 
因为这个应用有可能部署到多台机子上运行 有可能每台机子的绝对路径都不一样哦

**Comment by JesseYan** [comment]
我遇到过，IDE中执行，遇到此问题。在shell下，此文件的目录下OK。
可以在IDE中设置项目root路径。
